services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

  edw:
    image: postgres:16
    container_name: enterprise-dw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  glue-dev:
    build:
      context: .
      dockerfile: docker/glue/Dockerfile

    image: enterprise-glue-dev:5
    container_name: glue-dev

    command:
      - -c
      - >
        python3 -m jupyterlab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --ServerApp.root_dir=/home/hadoop/workspace

    working_dir: /home/hadoop/workspace

    ports:
      - "8888:8888"
      - "4040:4040"

    volumes:
      - .:/home/hadoop/workspace
      - ./docker/glue/jars:/opt/spark/jars

    env_file:
      - .env

    environment:
      PYTHONPATH: "/usr/share/aws/glue-pds:/usr/share/aws/glue-pds/PyGlue.zip:/home/hadoop/workspace/docker/glue"

    stdin_open: true
    tty: true

    depends_on:
      - sqlserver

volumes:
  sqlserver-data:
    external: true
    name: docker_sqlserver-data

  postgres-data:
    external: true
    name: docker_postgres-data